# selectInput("test", "Select:", c("1", "2")),
# dateInput("date", "Date", value = "2021-02-28"),
# dateRangeInput("daterange1", "Date range:",
#                start = "2001-01-01",
#                end   = "2010-12-31"),
# checkboxGroupInput("variable", "Variables to show:",
#                    c("Cylinders" = "cyl",
#                      "Transmission" = "am",
#                      "Gears" = "gear")),
# checkboxInput("somevalue", "Some value", FALSE),
# numericInput("obs", "Observations:", 10, min = 1, max = 100),
# radioButtons("dist", "Distribution type:",
#              c("Normal" = "norm",
#                "Uniform" = "unif",
#                "Log-normal" = "lnorm",
#                "Exponential" = "exp")),
# varSelectInput("variable", "Variable:", airbnb_data),
# submitButton("Update View", icon("refresh")),
# helpText("When you click the button above, you should see",
#          "the output below update to reflect the value you",
#          "entered at the top:")